# Generated by Django 5.1.3 on 2024-12-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedasset',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
