# Generated by Django 5.1.5 on 2025-02-03 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('identifier', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=30)),
                ('condition', models.CharField(choices=[('good condition', 'Good Condition'), ('under maintenance', 'Under Maintenance')], default='good condition', max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('good condition', 'Good Condition'), ('under maintenance', 'Under Maintenance')], default='other', max_length=30)),
                ('identifier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assets.asset')),
                ('enrollment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assets.staffextra')),
            ],
        ),
    ]
