# Generated by Django 5.1.5 on 2025-02-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
