# Generated by Django 5.1.5 on 2025-02-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_asset_is_issued_asset_requested_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_issued',
        ),
    ]
